name: Update GitHub Stats

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch: # 手動実行用

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: GitHub Readme Stats Force Update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # GitHub Stats の画像URLにタイムスタンプを付けてキャッシュを強制更新
          TIMESTAMP=$(date +%s)

          # README.mdを更新
          sed -i "s/\(username=Jakey08[^\"]*\)/\1?timestamp=$TIMESTAMP/g" README.md
      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update GitHub stats" || exit 0
          git push
